
version: '3.8'

services:
  front:
    image: gopikumar1/free-fe-image
    ports:
      - "5173:5173"
    restart: on-failure
    networks:
      - docswitch-free-net

  backend:
    image: gopikumar1/free-be-image
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./backend/.env
    networks:
      - docswitch-free-net

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - docswitch-free-net


networks:
  docswitch-free-net:
    external: true

volumes:
  mongo-data:


